"""


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"""


def even_fibonacci_numbers(limit):
    sum = 0
    a = 0
    b = 1 
    while a < limit:
        if a%2==0:
            sum=sum+a
        fib_num = a+b
        b = a
        a = fib_num
    print(sum)
even_fibonacci_numbers(4000000)    



